### ISSUE TITLE
Consider these additional upgrades

### ISSUE THREAD

**Issue by StookDog** [mikzorz/RuneScape-Gamification#5]
I've made a couple of upgrades to the script for fun. You could consider implementing some of these. I saw you recently made some upgrades based on my review on the anki website and I really appreciated that!

Ideas:
- Change heart "endurance" symbol to the one below so it is colored and matches the other symbols
- Consider implementing the following statistics in the pop-up like I have here. I copied the idea from the game and it just feels right.
![Screenshot_13](https://github.com/mikzorz/RuneScape-Gamification/assets/16076019/33f57b70-fe20-403c-b196-6b2982a89ea6)
- I completely changed the XP for all the skills so levelling feels more like RS where you can get to level 30-40 in maybe 5-10 hours of studying instead of 50x longer (Idk how others like the current XP rates but for me was painfully slow. Like ~13,000,000 reviews needed for a 99 seemed almost impossible, with this current setup a 99 should be ~260,000 reviews. Changed curiosity since I do many fewer new cards compared to reviews and allowed for "high xp drops" rarely. Made focus more generous since it's hard to stay focused long enough to build a big bonus but this has been very motivating to keep pushing through cards when you have a big bonus.)
- Consider adding a level up noise. I currently have it disabled but will enable it again when I get levels to the 70's so it's not so frequent.
- Added skill "Consistency": gets an increasing amount of XP for every consecutive DAY you study. At day 60 you will get 41k xp per day for continued streak. This will result in 99 at 365 day streak.

Thank you for your effort!

'import anki
import datetime
import json
import random
import threading
import time
import os

from aqt import gui_hooks, mw
# import the "show info" tool from utils.py
from aqt.utils import showInfo, qconnect
# import all of the Qt GUI library
from aqt.qt import *
from PyQt6 import QtCore, QtGui
from PyQt6.QtCore import QEasingCurve, QPropertyAnimation, QTimer, Qt, QRect
from PyQt6.QtGui import QFont
from PyQt6 import QtWidgets

# Path to the sound clip
SOUND_CLIP_PATH = "PATH_TO_FOLDER/Levelup.mp3"

# define the XP needed to reach each level
level_xp = [0, 83, 174, 276, 388, 512, 650, 801, 969, 1154, 1358, 1584, 1833, 2107, 2411, 2746, 3115, 3523, 3973, 4470, 5018, 5624, 6291, 7028, 7842, 8740, 9730, 10824, 12031, 13363, 14833, 16456, 18247, 20224, 22406, 24815, 27473, 30408, 33648, 37224, 41171, 45529, 50339, 55649, 61512, 67983, 75127, 83014, 91721, 101333, 111945, 123660, 136594, 150872, 166636, 184040, 203254, 224466, 247886, 273742, 302288, 333804, 368599, 407015, 449428, 496254, 547953, 605032, 668051, 737627, 814445, 899257, 992895, 1096278, 1210421, 1336443, 1475581, 1629200, 1798808, 1986068, 2192818, 2421087, 2673114, 2951373, 3258594, 3597792, 3972294, 4385776, 4842295, 5346332, 5902831, 6517253, 7195629, 7944614, 8771558, 9684577, 10692629, 11805606, 13034431]

# define skill names and labels
skill_symbols = {"focus": "🎯", "curiosity": "💡", "endurance": "❤️", "recall": "💾", "speed": "⚡", "consistency": "⏳"} #⚕ ⚖ ✚ »

# define a variable to keep track of the number of consecutive reviews the user has completed
consecutive_reviews = 30

# define a function to save the current state of the skills dictionary to a file
def save_skills():
    with open(skill_path + "/skills.json", "w") as f:
        json.dump(skills, f)

# define a function to load the saved state of the skills dictionary
def load_skills():
    global skills
    global skill_path
    skill_path = os.path.realpath(os.path.dirname(__file__) + "/user_files")
    try:
        with open(skill_path + "/skills.json", "r") as f:
            skills = json.load(f)
    except:
        skills = {"focus": {"level": 1, "xp": 0}, "curiosity": {"level": 1, "xp": 0}, "endurance": {"level": 1, "xp": 0}, "recall": {"level": 1, "xp": 0}, "speed": {"level": 1, "xp": 0}, "consistency": {"level": 1, "xp": 0}}

    if not all(skill in skills for skill in skill_symbols):
        # Add a dictionary entry for each missing skill
        for skill in skill_symbols:
            if skill not in skills:
                skills[skill] = {"level": 1, "xp": 0}
    
def skill_label_color_change(skill_label, duration):
    # sleep for 500 milliseconds
    time.sleep(duration)
    # reset the style sheet of the skill label
    #skill_label.setStyleSheet("color: white;")
    skill_label.setStyleSheet("")

def level_up(skill_label, skill):
    # get the dock widget
    dock = mw.findChild(QtWidgets.QDockWidget)    
    # get the label that displays the skill
    skill_label = dock.findChild(QtWidgets.QLabel, f"{skill}_label")
    # change the text color of the label to orange
    skill_label.setStyleSheet("color: green;")
    skill_label.setText("{} {}".format(skill_symbols[skill], skills[skill]["level"]))
    # create a thread to update the position of the skill label
    thread = threading.Thread(target=skill_label_color_change, args=(skill_label, 15))
    thread.start()  # start the thread
    
def level_up(skill_label, skill):
    # Debugging output
    print(f"Leveling up {skill}...")
    # get the dock widget
    dock = mw.findChild(QtWidgets.QDockWidget)    
    # get the label that displays the skill
    skill_label = dock.findChild(QtWidgets.QLabel, f"{skill}_label")
    # change the text color of the label to Green
    skill_label.setStyleSheet("color: green;")
    skill_label.setText("{} {}".format(skill_symbols[skill], skills[skill]["level"]))
    # create a thread to update the position of the skill label
    thread = threading.Thread(target=skill_label_color_change, args=(skill_label, 15))
    thread.start()  # start the thread
    # Debugging output
    print(f"Playing level up sound for {skill}...")
    #Play level up sound
    #play_level_up_sound()

def play_level_up_sound():
    # Play the sound
    anki.sound.play(SOUND_CLIP_PATH)
    # Pause for 1 seconds
    time.sleep(2.5)

def animate_xp_gain(skill):
    # get the dock widget
    dock = mw.findChild(QtWidgets.QDockWidget)
    # get the label that displays the skill
    skill_label = dock.findChild(QtWidgets.QLabel, f"{skill}_label")
    # change the text color of the label to orange
    skill_label.setStyleSheet("color: orange;")
    # create a thread to update the position of the skill label
    thread = threading.Thread(target=skill_label_color_change, args=(skill_label, 3))
    thread.start()  # start the thread

# define a function to increase the user's progress on a skill
def increase_skill_progress(skill, amount):
    if amount > 0:
       skills[skill]["xp"] += amount
       
    if skills[skill]["xp"] >= level_xp[skills[skill]["level"]]:
       skills[skill]["level"] += 1
       # No need to subtract the excess XP here
       # Remove this line: skills[skill]["xp"] -= level_xp[skills[skill]["level"] - 1]
       # get the dock widget
       dock = mw.findChild(QtWidgets.QDockWidget)
       # get the label that displays the skill
       skill_label = dock.findChild(QtWidgets.QLabel, f"{skill}_label")
       # update the text of the label to display the updated level
       # show the level up animation for the skill label
       level_up(skill_label, skill)
    elif amount > 0:
       animate_xp_gain(skill)
       
def update_skill_tool_tip(skill):
    # get the dock widget
    dock = mw.findChild(QtWidgets.QDockWidget)
    # get the label that displays the skill
    skill_label = dock.findChild(QtWidgets.QLabel, f"{skill}_label")
    # Calculate remaining XP to next level
    xp_remaining = level_xp[skills[skill]["level"]] - skills[skill]["xp"]
    # Calculate the total experience for the skill
    total_experience = skills[skill]["xp"]
    # Calculate the experience required for the current level
    xp_for_current_level = level_xp[skills[skill]["level"]-1]
    # Calculate the experience gained during this level
    experience_this_level = total_experience - xp_for_current_level
    # Calculate the total experience needed to advance to the next level
    xp_for_next_level = level_xp[skills[skill]["level"]]
    total_experience_needed = xp_for_next_level - xp_for_current_level
    xp_remaining = level_xp[skills[skill]["level"]] - skills[skill]["xp"]
    # update the tool tip for the label to display the updated skill level and XP of the tool tip
    skill_label.setToolTip("Level: {} (Current XP: {}, Next Lvl: {}, Remaining: {})".format(skills[skill]["level"], skills[skill]["xp"], abs(xp_for_next_level), xp_remaining))
       
# define a function to reset the consecutive reviews counter
def reset_consecutive_reviews():
    global consecutive_reviews
    consecutive_reviews = 30
 
#def on_show_question(reviewer, card, ease):
def on_show_question():
    global start_time
    start_time = datetime.datetime.now()

# define a function to track consecutive days of reviews
def track_consecutive_reviews():
    global streak_awarded_today
    streak_awarded_today = 0
    today = datetime.datetime.now().date()

    if "streak_days" not in skills:
        skills["streak_days"] = 0

    if "last_review_date" in skills:
        last_review_date = datetime.datetime.strptime(
            skills["last_review_date"], "%Y-%m-%d").date()
        if (today - last_review_date).days == 1:
            skills["streak_days"] += 1
        elif (today - last_review_date).days > 1:
            skills["streak_days"] = 1
        elif (today - last_review_date).days == 0:
            streak_awarded_today = 1
    else:
        skills["streak_days"] = 1

    skills["last_review_date"] = today.strftime("%Y-%m-%d")
    save_skills() 

#SPEED
#SPEED
#SPEED
# define a function to handle the completion of an Anki review
def on_show_answer():
    # determine the elapsed time between when the question was shown and when the user clicked the "Show Answer" button
    global elapsed_time
    elapsed_time = datetime.datetime.now() - start_time
    global elapsed_time_seconds 
    elapsed_time_seconds = elapsed_time.total_seconds()
    # determine the amount of XP to award for the "speed" skill based on the elapsed time
    speed_xp = 0
    if elapsed_time_seconds < 1:
        speed_xp = 500
    elif elapsed_time_seconds < 2:
        speed_xp = 400
    elif elapsed_time_seconds < 3:
        speed_xp = 300
    elif elapsed_time_seconds < 4:
        speed_xp = 200
    elif elapsed_time_seconds < 5:
        speed_xp = 100
    elif elapsed_time_seconds < 10:
        speed_xp = 75
    elif elapsed_time_seconds < 15:
        speed_xp = 65
    elif elapsed_time_seconds < 30:
        speed_xp = 50

    # increase the user's progress on the "speed" skill
    increase_skill_progress("speed", speed_xp)
    # update the tool tip for the label to display the updated "speed" level and XP
    update_skill_tool_tip("speed")

#FOCUS
#FOCUS
#FOCUS
def on_answer_button(reviewer, card, ease):
    if elapsed_time_seconds < 90:
        global consecutive_reviews
        # increment the consecutive reviews counter
        consecutive_reviews += 2
        increase_skill_progress("focus", consecutive_reviews)
        # get the label that displays the "focus" skill and update the tool tip label
        update_skill_tool_tip("focus")
    else:
        reset_consecutive_reviews()

#ENDURANCE
#ENDURANCE
#ENDURANCE 
    endurance_xp = 65
    increase_skill_progress("endurance", endurance_xp)
    # update the tool tip for the label to display the updated "endurance" level and XP
    update_skill_tool_tip("endurance")

#RECALL
#RECALL
#RECALL
     # determine the amount of XP to award for the "recall" skill based on the user's answer
    recall_xp = random.sample([0, 5, 10, 15, 20], k=1)
    if ease == 2:
        recall_xp = random.sample([25, 30, 35, 40, 45], k=1)
    elif ease == 3:
        recall_xp = random.sample([50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100], k=1)
    elif ease == 4:
        recall_xp = random.sample([200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000], k=1)
      
    # increase the user's progress on the "recall" skill
    increase_skill_progress("recall", recall_xp[0])
    update_skill_tool_tip("recall")

#CURIOSITY
#CURIOSITY
#CURIOSITY
    # Increase curiosity by 1 xp for new cards
    if card.ivl == 0:
        curiosity_xp = random.sample([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 250, 250, 250, 250, 250, 250, 250, 250, 250, 300, 300, 300, 300, 300, 300, 300, 300, 350, 350, 350, 350, 350, 350, 350, 400, 400, 400, 400, 400, 400, 450, 450, 450, 450, 450, 500, 500, 500, 750, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000, 6500, 7000, 7500, 8000, 8500, 9000, 9500, 10000], k=1)
        increase_skill_progress("curiosity", curiosity_xp[0])
        update_skill_tool_tip("curiosity")

#CONSISTENCY
#CONSISTENCY
#CONSISTENCY

    # Calculate consistency XP
    if streak_awarded_today == 0:
        if skills["streak_days"] <= 60:
            consistency_xp = 300 * skills["streak_days"]
        else:
            consistency_xp = 41000
    else:
        consistency_xp = 0

    # Increase consistency skill progress
    increase_skill_progress("consistency", consistency_xp)
    update_skill_tool_tip("consistency")

# define a function to display the skill levels on the Anki home screen
def display_skills_on_home_screen():
    global label
    # create a QDockWidget and set it to be floatable
    dock = QtWidgets.QDockWidget()
    dock.setFloating(True)
    # create a horizontal layout to hold the skill labels
    layout = QtWidgets.QVBoxLayout()
    # add the skill labels to the layout
    for skill, symbol in skill_symbols.items():
        label = QtWidgets.QLabel(f"{symbol} {skills[skill]['level']}")
        label.setObjectName(f"{skill}_label")
        label.setTextFormat(QtCore.Qt.TextFormat.RichText)
        
        # Calculate the total experience for the skill
        total_experience = skills[skill]["xp"]
        # Calculate the experience required for the current level
        xp_for_current_level = level_xp[skills[skill]["level"]-1]
        # Calculate the experience gained during this level
        experience_this_level = total_experience - xp_for_current_level
        # Calculate the total experience needed to advance to the next level
        xp_for_next_level = level_xp[skills[skill]["level"]]
        total_experience_needed = xp_for_next_level - xp_for_current_level
        xp_remaining = level_xp[skills[skill]["level"]] - skills[skill]["xp"]
        
        # Set the tool tip to display the experience gained during this level divided by the total experience needed for the next level
        label.setToolTip("Level: {} (Current XP: {}, Next Lvl: {}, Remaining: {})".format(skills[skill]["level"], skills[skill]["xp"], abs(xp_for_next_level), xp_remaining))
        layout.addWidget(label)

    # create a widget to hold the layout and add it to the dock
    widget = QtWidgets.QWidget()
    widget.setLayout(layout)
    dock.setWidget(widget)
    # add the dock to the main window
    mw.addDockWidget(QtCore.Qt.DockWidgetArea.RightDockWidgetArea, dock)
     
# pop up for debugging purposes
def debug_popup(y):
    # create a pop-up window with the specified message
    popup = QtWidgets.QMessageBox()
    popup.setWindowTitle("Debugging Pop-up")
    #popup.setWindowTitle(x)
    #popup.setText("Debugging Pop-up")
    popup.setText(y)
    popup.exec_()

class MyDialog(QtWidgets.QDialog):
    def __init__(self, parent=None) -> None:
        super().__init__(parent)
        label = QtWidgets.QLabel("""🎯 Focus: Gain compounding XP (+2) for consecutive reviews. 90 second time limit per review.

💡 Curiosity: Gain 100-10000 XP (randomly) for every card that changes from 'New' to 'Learning'.

❤️ Endurance: Gain 65 XP for every card reviewed.
                 
💾 Recall: Gain a random amount of XP for recalling cards correctly, increasing with each level of recall.

⚡ Speed: Gain XP for answering quickly. 500 for <1s, 400 for <2s, 300 for <3s, 200 for <4s, 100 for <5s, 75 for <5s, 65 for <10s, 50 for <15s. 

The XP needed to level up can be viewed by hovering over the relevant skill symbol.""")
        font = QtGui.QFont()
        font.setFamilies(["Noto Sans", "Noto Color Emoji"])
        font.setPointSize(10)
        label.setFont(font)
        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(label)
        self.setLayout(layout)

def add_menu():
    def info():
        mw.dialog = MyDialog()
        mw.dialog.show()
    
    # in case the user closes the dock
    def show_dock():
        # TODO
        pass

    action = QAction("RuneScape Gamification", mw)
    qconnect(action.triggered, info)
    mw.form.menuTools.addAction(action)

# load the saved state of the skills dictionary when the Anki add-on is started
anki.hooks.addHook("profileLoaded", load_skills)
# register a hook to call the display_skills_on_home_screen function when the Anki home screen is displayed
anki.hooks.addHook("profileLoaded", display_skills_on_home_screen)
# create a submenu within the Tools menu
anki.hooks.addHook("profileLoaded", add_menu)
# register a hook to call the on_showQuestion function when a card is first displayed
anki.hooks.addHook("showQuestion", on_show_question)
#gui_hooks.card_will_show.append(on_show_question)
# register a hook to call the on_review_complete function when a review is rated
anki.hooks.addHook("showAnswer", on_show_answer)
# register a hook to call the on_review_complete function when a review is completed
gui_hooks.reviewer_did_answer_card.append(on_answer_button)
gui_hooks.reviewer_will_end.append(reset_consecutive_reviews)
# register a hook to save the skills dictionary when the Anki program is closed
anki.hooks.addHook("unloadProfile", save_skills)
# register a hook to track consecutive reviews
anki.hooks.addHook("showAnswer", track_consecutive_reviews)'

**Comment by mikzorz** [comment]
Thank you for the detailed feedback! I'll make the changes when I have time, expect an update within a few days.

**Comment by mikzorz** [comment]
All of these should now be added (with tweaks) except for the sound effect. I'll open a separate issue for that and implement it later.
